version: 0.0.{build}

branches:
  only:
    # Releases must be built from a release tag
    - /^(?!master).+$/
    - /^master.+$/

image: Visual Studio 2017

test: off

build:
  publish_nuget: true

install:
  - cmd: git submodule update --init

build_script:
  - ps: .\build.ps1 -Target Package # -Verbosity Diagnostic -buildVerbosity=Verbose

artifacts:
  - path: YamlDotNet\bin\Release\netstandard1.3
    name: Release-NetStandard

  - path: YamlDotNet\bin\Release\net45
    name: Release-Net45

  - path: YamlDotNet\bin\Release\net35
    name: Release-Net35

  - path: YamlDotNet\bin\Release\net20
    name: Release-Net20

  - path: YamlDotNet\bin\Release\net40
    name: Release-UnitySubset-v35

  - path: YamlDotNet\bin\*.nupkg

for:
  - branches:
      only:
        - master
    skip_non_tags: true

    deploy:
      - provider: NuGet
        api_key:
          secure: GMc0xUTASI8qTPK1/eN/GFs6PBhPFBin1TT1hE5N8NlkU7VSBx3z4zQinSv/ICmx
        artifact: /.*\.nupkg/
