version: 0.0.{build}
branches:
  only:
    - master
    - release

os: Windows Server 2012 R2

install:
  - cmd: git submodule update --init
  - ps:  .\prebuild.ps1
  - cmd: nuget restore

platform: Any CPU
configuration:
  - Release
  - Release-Signed

build:
  publish_nuget: true

artifacts:
  - path: YamlDotNet\bin\$(configuration)
    name: YamlDotNet.dll

deploy:
  - provider: NuGet
    api_key:
      secure: GMc0xUTASI8qTPK1/eN/GFs6PBhPFBin1TT1hE5N8NlkU7VSBx3z4zQinSv/ICmx
    artifact: /.*\.nupkg/
    on:
      branch: release
