version: 0.0.{build}

image: Visual Studio 2022

test: off

environment:
  NUGET_API_KEY:
    secure: pomYNeSluKjzaqIYea800dn9dd/CZg5AOSJQnkpjFFxNO13qcA2l6KW/6dTxfQEb
  GITHUB_TOKEN:
    secure: /CkECN+K6CbiRXqvuvp7I6azoc43qx97kzyM8+7Xr84IB9sp5KqdIlb/04o/xlOt
  TWITTER_CONSUMER_API_KEY:
    secure: o4jM6NnXqtI3/Bzef2xpcTAOuPn/WwO+khiWvrbletk=
  TWITTER_CONSUMER_API_SECRET:
    secure: a4TQjB1vp0lRFZ7aA7RamHAhkHlPlMqdvsaZvzGs/pPkR+YfuGQ7AKlknD26HIE0xGUTi8M1wqffQUKJL1knHg==
  TWITTER_ACCESS_TOKEN:
    secure: TfgxKzf9AAbDuJmuYnnzjYKhHcxyYv7Z+AnFRzlQc5CcIJ3h52YZAokQGF3n3K8r21V1DxeKHc/qWG1yZs4NKg==
  TWITTER_ACCESS_TOKEN_SECRET:
    secure: aMvxmavbq8tylMDe8QGEdemNMPzrd7i6982i/iVydNYHhUvzV7lw5AJsiEpfRyzt

install:
  - cmd: git submodule update --init
  - cmd: dotnet tool install --global GitVersion.Tool

build_script:
  - cmd: .\build.cmd --appveyor

artifacts:
  - path: YamlDotNet\bin\Release\netstandard2.1
    name: Release-NetStandard-2.1

  - path: YamlDotNet\bin\Release\netstandard1.3
    name: Release-NetStandard-1.3

  - path: YamlDotNet\bin\Release\net45
    name: Release-Net45

  - path: YamlDotNet\bin\Release\net35
    name: Release-Net35

  - path: YamlDotNet\bin\Release\net20
    name: Release-Net20

  - path: YamlDotNet\bin\Release\net40
    name: Release-UnitySubset-v35

  - path: YamlDotNet\bin\*.nupkg
