name: Create a new release
on:
  workflow_dispatch:
    inputs:
      ref:
        description: Commit name to release (defaults to master)
        required: false
      args:
        description: Additional command line arguments
        required: false

jobs:
  release:
    name: Draft Release
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: ${{ github.event.inputs.ref }}

# Make sure the required versions of dotnet core on the server
    - name: Install dotnet 3.1
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 3.1.x

    - name: Install dotnet 6.0
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Install dotnet 7.0
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Install GitVersion.Tool
      run: dotnet tool install --global GitVersion.Tool

    - name: Create draft release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: ./build.sh CreateGithubRelease ${{ github.event.inputs.args }}
